#!/bin/bash
echo "即将开始一键安装CC环境"
yum install -y wget
yum install -y unzip
wget http://64.69.43.216/cc.zip 
unzip -o config.zip
wget https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz
tar xf  node-v10.16.0-linux-x64.tar.xz
cd node-v10.16.0-linux-x64/
ln -s ~/node-v10.16.0-linux-x64/bin/node /usr/bin/node
ln -s ~/node-v10.16.0-linux-x64/bin/npm /usr/bin/npm
ln -s ~/node-v10.16.0-linux-x64/bin/npm /usr/bin/npx
node -v 
cd
echo"安装完成!"